language: php

sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install

script:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; composer phpunit; fi;
  - if [[ ${TRAVIS_PHP_VERSION:0:3} != "5.6" ]]; composer test; fi;
